fix sqs message attributes quota reached when propagating
DataDog/dd-trace-js pull request #1096
Opened 2020-09-24 15:26 UTC by rochdev

### What does this PR do?

Fix SQS message attributes quota reached when propagating.

### Motivation

SQS has a quota of 10 on the number of message attributes. This means that if there are already 10 attributes and we add the one we need for propagation, we go beyond the limit which results in an error. This means that unfortunately for now propagation can only be supported for less than 10 existing message attributes until we find another way to propagate.

Fixes #1094

2020-09-24 15:31 UTC, jmclean-cnexus commented
Does this really fix the issue? From the looks, since an `else if` is used, you will still run into the issue.

2020-09-24 15:32 UTC, jmclean-cnexus commented
thank you for looking into this!

2020-09-24 15:48 UTC, rochdev commented
> Does this really fix the issue? From the looks, since an else if is used, you will still run into the issue.

The other condition is that there are no message attributes at all, meaning 0.

2020-09-24 15:57 UTC, jmclean-cnexus commented
Thanks @rochdev , I deleted my comment after realizing how preposterous it was.

2020-09-24 17:00 UTC, bengl requested changes

2020-09-24 17:01 UTC, rochdev commented on .vscode/settings.json
> +  "debug.node.autoAttach": "off"
It doesn't, I must have hit this by mistake, let me remove that.

2020-09-25 15:40 UTC, bengl commented on packages/datadog-plugin-aws-sdk/src/services/sqs.js
> +      } else if (Object.keys(request.params.MessageAttributes).length >= 10) { // SQS quota
This warrants a test, I think.

2020-09-25 15:53 UTC, rochdev commented on packages/datadog-plugin-aws-sdk/src/services/sqs.js
> +      } else if (Object.keys(request.params.MessageAttributes).length >= 10) { // SQS quota
Tests are still broken for AWS SDK.

2020-09-25 17:22 UTC, bengl approved these changes

2020-09-25 17:23 UTC, merged

2021-10-04 09:12 UTC, SuvabBaral commented
Hi @rochdev  is there a way we can disable this feature?
What I mean is that , is there any way, we can stop the tracer to append these trace details to the SQS queue messageAttributes?

2021-10-04 15:44 UTC, rochdev commented
@SuvabBaral Replied in https://github.com/DataDog/dd-trace-js/issues/846#issuecomment-933612476