fix possible app crash in latest when used with meteor 2.0
DataDog/dd-trace-js pull request #1233
Opened 2021-02-03 18:05 UTC by rochdev

### What does this PR do?

Fix possible app crash in latest when used with Meteor 2.0 by updating the tracer to default to the `async_resource` scope manager since the issue seems to be a bug in `AsyncLocalStorage`.

### Motivation

Applications using Meteor 2.0 with the tracer are experiencing random C++ errors. While it's still unclear why this is happening, switching to the `executionAsyncResource` based scope manager seems to resolve the issue.

Fixes #1229

2021-02-03 18:08 UTC, bengl requested changes

2021-02-03 18:08 UTC, bengl commented on packages/dd-trace/src/platform/node/index.js
> +    } else if (scope === scopes.ASYNC_RESOURCE || (!scope && hasSupportedAsyncLocalStorage)) {
This line seems wrong, now that you've swapped them? In particular, `hasSupportedAsyncLocalStorage`.

2021-02-03 18:41 UTC, bengl approved these changes
Lgtm

2021-02-03 22:19 UTC, merged

2021-04-02 16:17 UTC, schmod commented
Any clue if this was a performance regression, or if there are plans to restore `AsyncLocalStorage` as the default scope-manager?

2021-04-06 17:31 UTC, rochdev commented
@schmod The new scope manager basically does the same thing that `AsyncLocalStorage` itself does under the hood, and simply removes any additional logic that we don't need, some of which resulted in an incompatibility with `fibers` which Meteor uses. Because of that, it would be extremely unlikely to be slower than `AsyncLocalStorage` since it's basically a subset of the same code.