check against both params.body and params.bulkBody
DataDog/dd-trace-js pull request #1235
Opened 2021-02-05 21:43 UTC by ye-fan-cameo

### What does this PR do?
This PR will allow tracer to log bulkBody when it's a bulk request to endpoint like '/msearch' 

### Motivation
Since we switched the way to do multi-index search, we lose query.body in the dd log.

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes
In the later elasticsearch-js client, bulk request body is in bulkBody key:
https://github.com/elastic/elasticsearch-js/blob/883ef386e34c25f933835977328d8ae174b97a2a/api/api/msearch.js#L54

2021-02-06 18:59 UTC, rochdev requested changes

2021-02-06 18:59 UTC, rochdev commented on packages/datadog-plugin-elasticsearch/src/index.js
> +      if (params.body || params.bulkBody) {
There should be a corresponding test for this. Also, is it possible that both could be set or it's always one or the other?

2021-06-14 15:45 UTC, icharlie commented
Hi @rochdev 
Looks like @ye-fan-cameo is not working on this PR for a while. 
Can I create a separate PR to address this issue?

2021-06-14 21:17 UTC, rochdev commented
@icharlie Definitely, thanks for pushing this one to the finish line!

2021-06-15 16:31 UTC, rochdev commented
Superseded by #1423

2021-06-15 16:31 UTC, closed without merging