[ci-app][CIAPP-936] Add More Git Metadata to Tests
DataDog/dd-trace-js pull request #1254
Opened 2021-03-02 09:03 UTC by juan-fernandez

### What does this PR do?
* Add [`git-repo-info`](https://github.com/rwjblue/git-repo-info) which reads from the `.git` folder and does not rely on `git` command. 
   * The library itself is a [single file](https://github.com/rwjblue/git-repo-info/blob/master/index.js) with [no dependencies](https://github.com/rwjblue/git-repo-info/blob/master/package.json) so I think it is safe adding it.
* Use `git-repo-info` to add commit message, author date, name and email, and committer date, name and email to all tests. 

### Motivation
Be able to show rich commit metadata for clients that do not use our instrumented CIs: [CIAPP-936](https://datadoghq.atlassian.net/browse/CIAPP-936)

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2021-03-03 19:23 UTC, rochdev submitted a review, later dismissed

2021-03-04 07:08 UTC, juan-fernandez commented
@rochdev I'll delay this a bit to see if the maintainer of `git-repo-info` responds to my PR (https://github.com/rwjblue/git-repo-info/pull/60). There is a bug with multi line commit messages. If there's no response I'll have to figure out a solution.

2021-03-25 16:05 UTC, rochdev requested changes

2021-03-25 16:05 UTC, rochdev commented on .eslintignore
> +packages/dd-trace/src/plugins/util/git-repo-info.js
Could we move this to a vendor folder instead and ignore the entire folder?

2021-03-25 16:05 UTC, rochdev commented on packages/dd-trace/src/plugins/util/git-repo-info.js
> +// From https://github.com/rwjblue/git-repo-info/blob/d3ab418ef8b392eabbe911a37871708b15201b70/index.js
The file should also be added to `LICENSE-3rdparty.csv` similar to the TDigest entry.

2021-03-25 16:39 UTC, rochdev approved these changes

2021-03-25 16:52 UTC, merged