fix next request error when rendering directly
DataDog/dd-trace-js pull request #1538
Opened 2021-07-28 18:39 UTC by rochdev

### What does this PR do?

Fix next request error when rendering directly.

### Motivation

When rendering directly, there are cases where the request was not previously instrumented.

Fixes #1535

2021-07-28 20:38 UTC, Qard approved these changes

2021-08-03 15:49 UTC, bengl requested changes
Can you add a test?

2021-08-03 16:10 UTC, rochdev commented
> Can you add a test?

I was unable to reach this code path with everything I tried.

2021-08-03 19:06 UTC, bengl approved these changes

2021-08-03 19:06 UTC, merged