Fix timeout overflow warning
DataDog/dd-trace-js pull request #1693
Opened 2021-11-17 15:32 UTC by Qard

Simple logical error. It didn't quite match the algorithm the retry modules uses for computing its timeouts so it was getting out of sync.

Fixes #1685

2021-11-17 15:33 UTC, bmeck submitted a review, later dismissed

2021-11-17 15:36 UTC, rochdev requested changes
This is missing a test, especially since it was causing errors.

2021-12-09 19:36 UTC, rochdev approved these changes

2021-12-09 19:57 UTC, rochdev approved these changes

2021-12-09 20:17 UTC, rochdev approved these changes

2021-12-09 21:46 UTC, merged

2021-12-14 14:34 UTC, ruscon commented
@Qard we have this error on prod, witch version on dd-trace should we install for now ?

2021-12-14 15:38 UTC, rochdev commented
@ruscon We'll release a new version today.