Make Node.js typings consistent with engines and allow newer versions
DataDog/dd-trace-js pull request #1696
Opened 2021-11-19 08:24 UTC by bvanreeven

### What does this PR do?
* Make Node.js typings consistent with `engines` specification (`>=12`)
* Allow newer versions of node typings for use in projects that use e.g. Node.js 14 or 16

### Motivation
`yarn` kept installing version 10 of `@types/node` in the root `node_modules` directory of our project, resulting in compile errors.

2021-11-22 19:47 UTC, rochdev requested changes
Can this be pinned to 12? APIs from 14+ should not be used anyway since dd-trace supports 12.

2021-11-25 09:10 UTC, bvanreeven commented
@rochdev The `@types/node` package is an actual dependency of `dd-trace`, which means that pinning it to 12 does not solve the issue that the wrong version of Node typings are installed in projects _using_ `dd-trace`.

One way to work around this would be to remove the dependency on `@types/node` and have the following instead:
* A dev dependency on `@types/node@^12`
* A peer dependency on `@types/node@>=12`

This would result in the required restriction of supporting Node.js 12 for _development_ on `dd-trace`, while still allowing newer Node.js versions to be used in projects _using_ `dd-trace`.

The downside is that a peer dependency has to be added separately by the user IIRC.

2021-11-30 20:56 UTC, rochdev commented
This was actually added because it was causing problems for users of the library and not really for development. I don't remember why however, and I don't know TypeScript super well so I'll trust your judgement on this one.

2021-11-30 20:56 UTC, rochdev approved these changes

2021-11-30 20:57 UTC, merged