migrate knex to new plugin system
DataDog/dd-trace-js pull request #1844
Opened 2022-02-13 18:57 UTC by bengl

2022-02-14 17:40 UTC, rochdev submitted a review, later dismissed

2022-05-02 20:00 UTC, rochdev requested changes
The instrumentation should be added to `datadog-instrumentations/index.js`.

2022-05-02 20:15 UTC, bengl commented
@rochdev done in latest push.

2022-05-02 20:33 UTC, rochdev approved these changes

2022-05-02 20:36 UTC, merged