migrate sharedb to new plugin system
DataDog/dd-trace-js pull request #1849
Opened 2022-02-15 15:56 UTC by khanayan123

### What does this PR do?
migrate sharedb to new plugin system

### Motivation
migrate plugins to new plugin system

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2022-02-15 20:53 UTC, bengl commented on packages/datadog-instrumentations/src/sharedb.js
> +    callback = asyncResource.bind(callback)
Do you actually need this, given that you're wrapping everything on line 50 in a bind anyway?

2022-02-15 20:56 UTC, bengl requested changes

2022-02-15 20:56 UTC, bengl commented on packages/datadog-instrumentations/src/sharedb.js
> +    callback = asyncResource.bind(callback)
Do you actually need this, given that you're wrapping everything in a bind on line 50 anyway?

2022-02-15 20:56 UTC, bengl commented on packages/datadog-plugin-sharedb/src/index.js
> +      analyticsSampler.sample(span, this.config.measured)
Is this needed? The previous code doesn't seem to have used analytics sampler. Am I missing something here?

2022-02-15 21:25 UTC, rochdev requested changes

2022-02-16 14:48 UTC, bengl commented on packages/datadog-instrumentations/src/sharedb.js
> +    callback = asyncResource.bind(callback)
Nevermind, this was explained to me.

2022-02-22 20:21 UTC, rochdev approved these changes

2022-02-23 15:48 UTC, bengl approved these changes

2022-02-23 15:48 UTC, merged