remove datadog private properties from web plugins
DataDog/dd-trace-js pull request #1861
Opened 2022-02-21 19:03 UTC by rochdev

### What does this PR do?

Remove Datadog private properties from Web plugins.

### Motivation

When logging objects that contain references to tracer objects, it can add significant noise, and in some cases even performance issues or crashes. These properties should be completely unavailable from the user code.

2022-02-21 19:37 UTC, simon-id requested changes

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
>        expect(Reporter.reportAttack('', new Map([['req', {}]]))).to.be.false
```suggestion
      const req = {}
      expect(Reporter.reportAttack('', new Map([['req', req]]))).to.be.false
      expect(web.root).to.have.been.calledOnceWith(req)
```

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
```suggestion
      expect(web.root).to.have.been.calledOnceWith(req)

```

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
> +      span.context()._tags = { '_dd.origin': 'tracer' }
Interesting. Object mutation is like Pi, it has many uses where you least expect it.

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
```suggestion
      expect(web.root).to.have.been.calledOnceWith(req)

```

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
```suggestion
      expect(web.root).to.have.been.calledOnceWith(req)

```

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
>        expect(Reporter.finishAttacks({}, {})).to.be.false
```suggestion
      const req = {}
      expect(Reporter.finishAttacks(req, {})).to.be.false
      expect(web.root).to.have.been.calledOnceWith(req)
```

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
```suggestion
      expect(web.root).to.have.been.calledOnceWith(req)

```

2022-02-21 19:37 UTC, simon-id commented on packages/dd-trace/test/appsec/reporter.spec.js
```suggestion
      expect(web.root).to.have.been.calledOnceWith(req)

```

2022-02-21 20:50 UTC, simon-id approved these changes

2022-02-24 20:11 UTC, bengl approved these changes

2022-02-24 20:51 UTC, merged