migrate pg to new plugin system
DataDog/dd-trace-js pull request #1865
Opened 2022-02-23 14:26 UTC by khanayan123

### What does this PR do?
migrates postgres to new plugin system

### Motivation
to convert plugins to new plugin system

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2022-02-23 15:44 UTC, bengl requested changes

2022-02-23 15:44 UTC, bengl commented on packages/datadog-instrumentations/src/pg.js
> +        // originalCallback(err, res)
Unnecessary comment.

2022-02-23 15:44 UTC, bengl commented on packages/datadog-plugin-pg/src/t_index.js
> +'use strict'
You probably intended to delete this file.

2022-03-18 16:11 UTC, rochdev requested changes

2022-03-18 16:11 UTC, rochdev commented on packages/datadog-instrumentations/src/pg.js
> +    const finish = function (error) {
This should be bound explicitly.

2022-03-18 16:11 UTC, rochdev commented on packages/datadog-instrumentations/src/pg.js
> +    const finish = function (error) {
Just saw it's bound later, but let's bind it here instead to avoid multiple bindings.

2022-03-18 17:33 UTC, rochdev commented on packages/datadog-instrumentations/src/pg.js
> +      pgQuery.callback = AsyncResource.bind(function (err, res) {
This bind is no longer needed since both the callback and finish are bound above.

2022-03-18 17:40 UTC, bengl submitted a review, later dismissed

2022-03-18 18:57 UTC, rochdev approved these changes

2022-03-18 19:31 UTC, merged