migrate rhea to new plugin system
DataDog/dd-trace-js pull request #1895
Opened 2022-03-07 16:35 UTC by khanayan123

### What does this PR do?
migrates rhea to new plugin system

### Motivation
convert existing plugins to new plugin system

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2022-03-10 00:40 UTC, rochdev requested changes

2022-03-10 00:40 UTC, rochdev commented on packages/datadog-instrumentations/src/rhea.js
> +        msgObj.delivery[dd] = { asyncResource }
I removed this kind of reference from the code base a couple of weeks ago but it seems I forgot this one. We should never add any properties to library objects. A WeakMap can be used instead.

2022-03-10 00:40 UTC, rochdev commented on packages/datadog-instrumentations/src/rhea.js
> +function getResourceNameFromSender (sender) {
A resource name is a tracing concept and shouldn't be present in the instrumentation.

2022-03-10 00:40 UTC, rochdev commented on packages/datadog-instrumentations/src/rhea.js
> +    const cb = obj[dd].asyncResource.bind(update)
Similar to the above, we should never add properties to library objects.

2022-03-10 00:40 UTC, rochdev commented on packages/datadog-instrumentations/src/rhea.js
> +    const cb = obj[dd].asyncResource.bind(update)
There are several other occurrences of this as well.

2022-03-10 00:40 UTC, rochdev commented on packages/datadog-plugin-rhea/src/index.js
> +    this.addSub(`apm:rhea:general:async-end`, () => {
General?

2022-03-14 16:50 UTC, rochdev requested changes

2022-03-14 16:50 UTC, rochdev commented on packages/datadog-plugin-rhea/src/index.js
> +  if (sender.options && sender.options.target && sender.options.target.address) {
This should be normalized so that the subscriber can get the information without knowing the implementation details.

2022-03-14 16:50 UTC, rochdev commented on packages/datadog-plugin-rhea/src/index.js
> +    const res = tracer.extract('text_map', msgObj.message.delivery_annotations)
The variable is unnecessary.

2022-03-14 16:50 UTC, rochdev commented on packages/datadog-plugin-rhea/src/index.js
> +      const childOf = getAnnotations(msgObj, this.tracer)
This function name is confusing as it doesn't return annotations.

2022-03-17 21:50 UTC, rochdev approved these changes

2022-03-17 21:52 UTC, merged

2023-11-30 18:22 UTC, tlhunter commented on packages/datadog-plugin-rhea/src/index.js
> -  delivery[dd].connection = connection
This appears to be the line that was lost in the refactor, leading to the Rhea memory leak.