dont send traces to agent for routes on blocklist
DataDog/dd-trace-js pull request #1989
Opened 2022-04-08 18:49 UTC by khanayan123

### What does this PR do?
don't send traces to agent for routes on blocklist

### Motivation
to fix a regression in pkg version 2.x.x where tracer would still export traces to agent for routers that were on blocklist

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2022-04-08 19:52 UTC, rochdev requested changes

2022-04-08 19:52 UTC, rochdev commented on packages/datadog-plugin-http/src/server.js
> +      if (!this.config.blocklist || traces.length === 0) return undefined
`undefined` is redundant as it's the default.

2022-04-08 19:52 UTC, rochdev commented on packages/datadog-plugin-http/src/server.js
> +      if (this.config.blocklist.includes(urlParts.pathname)) {
What about `allowlist`?

2022-04-08 19:52 UTC, rochdev commented on packages/datadog-plugin-http/src/server.js
> +      if (!this.config.blocklist || traces.length === 0) return undefined
There should also be an additional check that the root span is actually an HTTP request.

2022-04-08 19:52 UTC, rochdev commented on packages/datadog-plugin-http/src/server.js
> +    this.addSub('datadog:tracer:trace:finish', ({ traces }) => {
`traces` should be `trace` or `spans`.

2022-04-08 19:52 UTC, rochdev commented on packages/datadog-plugin-http/test/server.spec.js
> +            .use((traces, spy) => {
This should be calling the spy, otherwise this test will always pass even if there is a request to the agent.

2022-04-08 19:52 UTC, rochdev commented on packages/datadog-plugin-http/test/server.spec.js
> +        expect(spy).to.not.have.been.called
The expect should be in the timer otherwise this will always be true.

2022-04-12 15:30 UTC, rochdev requested changes

2022-04-13 17:31 UTC, khanayan123 commented on packages/datadog-plugin-http/src/server.js
> +      const urlParts = url.parse(spans[0].meta['http.url'])
blocklist array only contain the endpoints and not the full url, so I assume we would need to parse?

2022-04-14 21:11 UTC, bengl requested changes

2022-04-14 21:11 UTC, bengl commented on packages/datadog-plugin-http/src/server.js
> +      const urlParts = url.parse(spans[0].meta['http.url'])
OK, but let's use the URL constructor here.

2022-04-14 21:11 UTC, bengl commented on packages/datadog-plugin-http/test/server.spec.js
> +          .then(done)
If a trace is received before 100ms, this test will pass. As an alternative here, try removing the `then`. The only success case here should be when the spy has not been called after 100ms.

2022-04-20 19:09 UTC, rochdev approved these changes

2022-04-22 14:26 UTC, bengl approved these changes

2022-04-22 14:47 UTC, merged