[ci-visibility] Support `mocha` test suites
DataDog/dd-trace-js pull request #2172
Opened 2022-07-10 09:57 UTC by juan-fernandez

### What does this PR do?
⚠️ WIP: do not review yet 

### Motivation

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2022-07-12 20:03 UTC, rochdev requested changes
The PR looks good for the most part, but there are several event listeners that are not explicitly bound to an `AsyncResource`. This could mean disconnected traces or spans that would never finish in some case. Any time an event is published on a channel it should always be bound to ensure it will be in the right scope regardless of where it was emitted.

2022-07-13 11:05 UTC, juan-fernandez commented
> The PR looks good for the most part, but there are several event listeners that are not explicitly bound to an `AsyncResource`. This could mean disconnected traces or spans that would never finish in some case. Any time an event is published on a channel it should always be bound to ensure it will be in the right scope regardless of where it was emitted.

good catch. That should be fixed in https://github.com/DataDog/dd-trace-js/pull/2172/commits/dfcda0ae3e63c2bcaf3ead80fe5cdc838ca39302

2022-07-13 14:40 UTC, rochdev approved these changes

2022-07-13 15:27 UTC, juan-fernandez commented
let's hold off on merging this for a bit until we figure out a potential issue in the intake

2022-07-18 15:57 UTC, juan-fernandez commented on packages/dd-trace/src/encode/agentless-ci-visibility.js
> +    // only for v2
Add `TODO` here: explain why this is needed and that it needs a solution

2022-07-18 16:28 UTC, juan-fernandez commented
added the TODO comment. Now solving the conflict

2022-07-18 17:34 UTC, rochdev approved these changes

2022-07-19 07:26 UTC, merged