Report weak cipher vulnerability
DataDog/dd-trace-js pull request #2342
Opened 2022-09-02 13:28 UTC by CarlesDD

### What does this PR do?
Provide a feature to analyze cipher used in crypto cipher functions and report the vulnerable (weak) ones.

### Motivation
Library side vulnerability detection

- [ ] Unit tests.

2022-09-02 15:18 UTC, uurien requested changes

2022-09-02 15:18 UTC, uurien commented on packages/datadog-instrumentations/src/crypto.js
> +      if (channel.hasSubscribers) {
Is not easier to understand with only one `if`?
```
if (channel.hasSubscribers && arguments.length > 0) {
```

2022-09-02 15:18 UTC, uurien commented on packages/dd-trace/src/appsec/iast/analyzers/weak-cipher-analyzer.js
> +const INSECURE_CIPHERS = [
In `weak-hash-analyzer.js` we have changed it by a `Set`. We should do the same here.

2022-09-05 08:17 UTC, iunanua approved these changes

2022-09-05 09:49 UTC, uurien commented on packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
> +  'WEAK_HASH_ANALYZER': require('./weak-hash-analyzer'),
In other files with multiple exports, they are ordered by name, `WEAK_CIPHER_ANALYZER` before `WEAK_HASH_ANALYZER`

2022-09-05 10:32 UTC, uurien approved these changes

2022-09-06 23:19 UTC, rochdev approved these changes

2022-09-07 14:19 UTC, uurien approved these changes

2022-09-07 14:22 UTC, merged