throw on error in next.js
DataDog/dd-trace-js pull request #2424
Opened 2022-10-03 22:26 UTC by tlhunter

### What does this PR do?

Modifies the next.js instrumentation so that when a handler throws an error, the error is re-thrown within the error handler.

### Motivation

Discussion with @rochdev about some customer issues we were seeing.

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

2022-10-04 01:16 UTC, rochdev requested changes

2022-10-04 01:16 UTC, rochdev commented on packages/datadog-instrumentations/src/next.js
> +      throw finish(req, res, null, e)
This should be tested to avoid regressions.

2022-10-05 23:14 UTC, tlhunter commented on packages/datadog-plugin-next/test/server.js
> -    if (req.path === '/exit') {
There is no such thing as `req.path`. This code appears unused anyway.

2022-10-06 16:11 UTC, tlhunter commented
At this point I'm not confident that this PR solves or changes anything. When setting `minimalMode: true` in the Next configuration I still can't get the handler promise to reject.

2022-10-06 17:44 UTC, rochdev commented on packages/datadog-plugin-next/test/index.spec.js
> +              .get(`http://localhost:${port}/puke`)
```suggestion
              .get(`http://localhost:${port}/boom`)
```

2022-10-06 17:44 UTC, rochdev approved these changes

2022-10-06 17:58 UTC, rochdev approved these changes

2022-10-06 18:02 UTC, merged