Accept space- and comma- separated tags
DataDog/dd-trace-js pull request #2435
Opened 2022-10-11 11:25 UTC by LoneRifle

### What does this PR do?
Modify tagger.js to recognise spaces as well as commas as a tag separator, 
using a regular expression to split `keyValuePairs`

### Motivation
This PR is made to be consistent with DataDog/dd-trace-rb#2011, 
DataDog/dd-trace-java#2011 and DataDog/dd-trace-py#2196. These 
PRs collectively recognise the support of spaces and commas to
separate tags in the `DD_TAGS` env var supported by datadog-agent.

### Other notes
Given we are in the middle of Hacktoberfest, I would like to request that
this PR is labelled with `hacktoberfest-accepted`, so that it can count
towards my contributions for the event.

2022-10-11 14:07 UTC, rochdev requested changes
Spaces are allowed in tag values, wouldn't this PR break that? The way the regular expression is currently tested it also looks like it would accept a sequence of commas and/or spaces as a separator, which would be invalid.

2022-10-12 00:35 UTC, LoneRifle commented
Sure. I'll port the impls from the Java client, which seems pretty robust.

The Java client will be chosen as a reference, because the Ruby and Python clients do not seem to be kind towards tag names/values with spaces in them even though Datadog can take those by coercing them into underscore.

2022-10-13 00:19 UTC, LoneRifle commented
@rochdev - have made changes taking reference from the Python client. Would you be happy to take a look again?

2022-10-20 23:17 UTC, LoneRifle commented
@rochdev - I've made changes as requested, using the Python client as a reference, notably choosing a separator based on the number of resulting tags and comparing it against the number of tag separators, ie `:`. Please have a look when you have the chance!

2022-10-24 14:32 UTC, rochdev commented
@LoneRifle We had a chat internally and it seems that some languages added this just to be compatible with the agent environment variable of the same name. This is useful mostly in languages where the environment are usually set on the system instead of the process. We unfortunately don't have a clear specification of how this should be handled across languages, so we unfortunately cannot accept this PR at this time. I'll still leave it open so that your work can be pushed to the finish line once we have a clear spec of how this environment variable should work going forward.

2024-01-02 11:03 UTC, closed without merging