V2.23.0 proposal
DataDog/dd-trace-js pull request #2637
Opened 2022-12-22 23:21 UTC by Qard

The v2.x branch is also missing a bunch of stuff, but that's somewhat expected due to semver-majors and semver-major-dependent changes not getting backported.

2022-12-22 23:52 UTC, tlhunter submitted a review, later dismissed

2022-12-23 01:05 UTC, Qard commented
Apparently #2601 can't be backported as `eslint-plugin-mocha` has an engine field limit of 14+. 😐

2022-12-23 08:13 UTC, juan-fernandez requested changes
the commits from these four PRs are missing. I guess there are conflicts? 
https://github.com/DataDog/dd-trace-js/pull/2584
https://github.com/DataDog/dd-trace-js/pull/2566
https://github.com/DataDog/dd-trace-js/pull/2608
https://github.com/DataDog/dd-trace-js/pull/2619

I'll have a look at the conflicts and let you know ASAP

2023-01-03 14:30 UTC, juan-fernandez approved these changes

2023-01-04 08:33 UTC, uurien approved these changes

2023-01-04 09:45 UTC, uurien approved these changes

2023-01-04 09:46 UTC, merged