v2.23.0 proposal fix conflicts
DataDog/dd-trace-js pull request #2638
Opened 2022-12-23 09:29 UTC by juan-fernandez

### What does this PR do?

### Motivation

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2022-12-23 19:01 UTC, Qard commented
Seems to be a lot of failures due to `promises` being `undefined`. 🤔

2022-12-28 23:43 UTC, iunanua requested changes

2022-12-28 23:43 UTC, iunanua commented on package.json
> +    "@datadog/native-iast-rewriter": "1.1.2",
Sorry, but we cannot jump from 1.0.0 to 1.1.2. I have to discuss a better solution with @uurien and @CarlesDD

2022-12-29 09:55 UTC, iunanua approved these changes

2023-01-03 13:56 UTC, merged