Remove unhandled wrap() typescript method overload
DataDog/dd-trace-js pull request #2914
Opened 2023-03-20 15:25 UTC by erictheswift

When using library, noticed that actual implementation of tracer.wrap does not seem to handle 'requiresParent' third boolean arg and just returns boolean as a result https://github.com/DataDog/dd-trace-js/blob/9f753ce63d6ec7528eb21cec82ac18943c7315c6/packages/dd-trace/src/tracer.js#L71-L105

2023-03-20 17:15 UTC, rochdev submitted a review, later dismissed

2023-03-20 18:38 UTC, Qard approved these changes

2023-03-20 19:19 UTC, Qard requested changes
Actually, looks like `docs/test.ts` also needs updating to match as it includes a bunch of `name, fn` checks which fail after this change.

2023-03-20 19:20 UTC, rochdev commented
It looks like the TypeScript tests are failing, I think one of the tests relies on the last argument being optional? The tests are in `docs/test.ts` and the tests can be run with `yarn type:test`.

2023-03-22 12:06 UTC, erictheswift commented
Some checks are failling because of lack of permissions or
>DD_API_KEY is missing in env, please add it.

Do I need to do anything with it?

2023-03-22 15:30 UTC, rochdev commented
> Do I need to do anything with it?

No, these are tests that can only run in branches to the repo itself and not on forks. They don't test anything TypeScript related so this change is safe for those.

2023-03-22 15:36 UTC, rochdev approved these changes

2023-03-22 19:34 UTC, Qard approved these changes

2023-03-22 22:18 UTC, merged