Add validation for git metadata env vars
DataDog/dd-trace-js pull request #3325
Opened 2023-06-30 13:23 UTC by ericlaz

### What does this PR do?
Provide validation for env vars like `DD_GIT_REPOSITORY_URL` and `DD_GIT_COMMIT_SHA` in order to simplify the user-provided Git metadata input process.

### Motivation
Reduce confusion and inform users if user-provided metadata is invalid.
### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2023-07-03 11:07 UTC, juan-fernandez reviewed
great job! And tests look very good 😄

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/src/plugins/util/user-provided-git.js
> +}
logging an error is a good idea, but we want to end up doing is removing the invalid values. We could do something like what we do with `removeEmptyValues`
```suggestion
function removeInvalidGitMetadata (metadata) {
  return Object.keys(metadata).reduce((filteredTags, tag) => {
    if (tag === GIT_REPOSITORY_URL) {
      if (!validateGitRepositoryUrl(metadata[GIT_REPOSITORY_URL])) {
        log.error('DD_GIT_COMMIT_SHA must be a full-length git SHA')
        return filteredTags
      }
    }
    if (tag === GIT_COMMIT_SHA) {
      if (!validateGitCommitSha(metadata[GIT_COMMIT_SHA])) {
        log.error('DD_GIT_REPOSITORY_URL must be a valid URL')
        return filteredTags
      }
    }
    filteredTags[tag] = metadata[tag]
    return filteredTags
  }, {})
}
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/src/plugins/util/user-provided-git.js
> +  return metadata
with the above suggestion, we could do 
```suggestion
  return removeInvalidGitMetadata(metadata)
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +  it('should return false if Git repository URL is invalid', (done) => {
`done` is only used when tests are asynchronous, but this is not the case here, so we can remove it 
```suggestion
  it('should return false if Git repository URL is invalid', () => {
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +    done()
```suggestion
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +  it('should return true if Git repository URL is valid', (done) => {
```suggestion
  it('should return true if Git repository URL is valid', () => {
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +    done()
```suggestion
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +    done()
```suggestion
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +  it('should return false if Git commit SHA is invalid', (done) => {
```suggestion
  it('should return false if Git commit SHA is invalid', () => {
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +  it('should return true if Git commit SHA is valid', (done) => {
```suggestion
  it('should return true if Git commit SHA is valid', () => {
```

2023-07-03 11:07 UTC, juan-fernandez commented on packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
> +    done()
```suggestion
```

2023-07-03 14:33 UTC, uurien requested changes

2023-07-03 14:33 UTC, uurien commented on packages/dd-trace/src/plugins/util/user-provided-git.js
> +  return /((http|git|ssh|http(s)|file|\/?)|(git@[\w.]+))(:(\/\/)?)([\w.@:/\-~]+)(\.git)(\/)?/.test(repoUrl)
why is a group the `s` of `http(s)`?
and this regex accepts things like `/://aaa.git` is this expected?

2023-07-03 14:33 UTC, uurien commented on packages/dd-trace/src/plugins/util/user-provided-git.js
> +        log.error('DD_GIT_REPOSITORY_URL must be a valid URL')
Mixed log messages:
```suggestion
        log.error('DD_GIT_REPOSITORY_URL must be a valid URL')
        return filteredTags
      }
    }
    if (tag === GIT_COMMIT_SHA) {
      if (!validateGitCommitSha(metadata[GIT_COMMIT_SHA])) {
        log.error('DD_GIT_COMMIT_SHA must be a full-length git SHA')
```

2023-07-04 10:19 UTC, juan-fernandez commented on LICENSE-3rdparty.csv
> -file,aws-lambda-nodejs-runtime-interface-client,Apache 2.0,Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
unrelated fix. This allows github to render this nicely: https://github.com/DataDog/dd-trace-js/blob/eric-navarro/validate-git-metadata/LICENSE-3rdparty.csv

2023-07-04 10:49 UTC, uurien approved these changes

2023-07-04 10:56 UTC, juan-fernandez approved these changes

2023-07-04 12:16 UTC, merged