increase the timeout time for esm tests to reduce test flakiness
DataDog/dd-trace-js pull request #3600
Opened 2023-08-29 19:02 UTC by khanayan123

### What does this PR do?
increase the timeout time for esm tests to reduce test flakiness

### Motivation
esm tests failing on release branches

2023-08-29 19:35 UTC, sabrenner requested changes

2023-08-29 19:35 UTC, sabrenner commented on integration-tests/cucumber/cucumber.spec.js
> +      }).tim
should this be `timeout`?

2023-08-29 20:06 UTC, sabrenner approved these changes

2023-08-29 20:07 UTC, tlhunter approved these changes

2023-08-29 20:26 UTC, sabrenner approved these changes

2023-08-29 20:31 UTC, tlhunter approved these changes

2023-08-30 07:25 UTC, juan-fernandez reviewed
are CI tests timing out because they're slow? Sometimes when actual failures happen they surface as timeouts. This change would just make it worse

2023-08-31 10:43 UTC, juan-fernandez approved these changes
I don't want to block if we think this is causing issues but I'd want to make sure the timeouts we see are actual timeouts or other issues that surface as timeouts. If it's the latter, this is just making it worse.

2023-08-31 13:44 UTC, khanayan123 commented
> I don't want to block if we think this is causing issues but I'd want to make sure the timeouts we see are actual timeouts or other issues that surface as timeouts. If it's the latter, this is just making it worse.

From my experience, I'd say the timeout errors are usually nothing more then just issues related to running tests in the CI where some runs are faster/slower then others and can cause timing issues. Usually anything deeper would be a bit more consistent rather then an occasional timeout failure. Although if you do feel strongly about it, we can not merge in the timeout change since the timeout errors usually only happen very infrequently and in those cases we can just rerun the job.

2023-08-31 18:29 UTC, merged