Check for processor to exist before accessing it in crash situations
DataDog/dd-trace-js pull request #3696
Opened 2023-10-10 12:23 UTC by kampka

### What does this PR do?
In crash situations, a race condition can cause the processor of a tracer to be called before it is set up, leading to unwanted failure cases.

### Motivation
When having a lambda function time out very quickly, it can happen that the tracer is not fully initialized before the `crashFlush` function is called, failing to complete the code block with the following error
```
Cannot read properties of undefined (reading 'killAll')
stack:
TypeError: Cannot read properties of undefined (reading 'killAll'),
    at crashFlush (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/lambda/handler.js:56:21),
    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/lambda/handler.js:14:3,
    at Channel.publish (node:diagnostics_channel:56:9),
    at Timeout._onTimeout (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/lambda/handler.js:32:20),
    at listOnTimeout (node:internal/timers:569:17),
    at process.processTimers (node:internal/timers:512:7)

```

2023-10-10 19:52 UTC, Qard requested changes
Seems to be a whole lot of unrelated changes here which don't match our code style. Also could use a test.

2023-10-11 07:08 UTC, kampka commented
@Qard thanks for the review

Looks like my editor applied some unintentional formatting to the file, sorry about that.
The diff should be much cleaner now.

> Also could use a test.

Given that this is a side effect issue, I have some difficulty crafting a useful test to reproduce this.
I could of course write a unit test, but that would probably be rather shallow and not very meaningful given the context of the change. What do you think?

2023-10-11 16:36 UTC, Qard commented
A unit test is fine. Just want to have something to catch that this does not regress in future changes.

2023-10-23 08:43 UTC, kampka commented
> Why does this happen in the first place? It seems like a reasonable expectation that the processor exists by that point.

That is a very good question and I haven't really managed to understand it myself.
The code paths involved are a little confusing because we generally use `dd-trace` as part of `dd-lambda-js` which inializes `dd-trace` which then patches over the `datadog` method of `dd-lambda-js` ( maybe ? )

So any insights into this would also be very much appreciated.

2023-10-24 00:41 UTC, rochdev commented
@kampka So this only happens when dd-trace-js is used with dd-lambda-js?

2023-10-24 08:10 UTC, kampka commented
> @kampka So this only happens when dd-trace-js is used with dd-lambda-js?

I assume yes. As far as I can tell, the timer invoking that code path is only ever set up in the `datadog` function of the lambda handler: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/lambda/handler.js#L88

2023-11-07 15:54 UTC, rochdev commented
@astuyve Any ideas what the problem could be? I'd rather see the underlying issue be fixed.

2024-04-30 14:29 UTC, kampka commented
I'll close this PR as I am no longer with the project where we encountered these issues. Feel free to pick my change if it helps and publish it however you feel it's useful.

2024-04-30 14:29 UTC, closed without merging