[profiling]  Add thread id labels to heap and wall profiles
DataDog/dd-trace-js pull request #3888
Opened 2023-12-15 14:37 UTC by nsavoire

### What does this PR do?
Add thread id labels (`thread id` for the worker thread id and `os thread id` for native thread id) to wall and heap profiles.

### Motivation
Allow to identify in the UI from which worker thread the profile is emitted.

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

### Security 
Datadog employees:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2023-12-18 12:19 UTC, Qard requested changes
Other than this accidental rename, LGTM.

2023-12-18 12:19 UTC, Qard commented on packages/dd-trace/src/profiling/profilers/events.js
> +    const timestampLabelKey = stringTable.dedup(END_TIMESTAMP_LABEL)
This change seems unintentional?

2023-12-18 16:02 UTC, nsavoire commented on packages/dd-trace/src/profiling/profilers/events.js
> +    const timestampLabelKey = stringTable.dedup(END_TIMESTAMP_LABEL)
Woops, badly fixed merge conflict

2023-12-18 21:50 UTC, nsavoire commented on packages/dd-trace/src/profiling/profilers/events.js
> +    const timestampLabelKey = stringTable.dedup(END_TIMESTAMP_LABEL)
Fixed

2023-12-19 15:06 UTC, Qard submitted a review, later dismissed

2023-12-19 16:50 UTC, szegedi approved these changes
LGTM, with a nit that you can fix if you want to

2023-12-20 08:42 UTC, Qard approved these changes

2023-12-20 10:25 UTC, szegedi approved these changes
🚢

2023-12-20 10:36 UTC, merged