Improve index.d.ts for NodeNext
DataDog/dd-trace-js pull request #3937
Opened 2024-01-05 21:33 UTC by benasher44

### What does this PR do?
Fixes #3264

### Motivation
Improve support for NodeNext (newer TypeScript module resolution)

### Plugin Checklist

- [ ] Unit tests.
- [x] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

### Security 
Datadog employees:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2024-01-08 21:33 UTC, benasher44 commented
@khanayan123 this should be semver-patch, but I don't have the ability to add labels.

Also this diff is large, but it's pretty easy to review if you hide whitespace changes:

<img width="306" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/1120429/bc3e066f-04e9-48d8-8369-5b41acca6f1d">

2024-01-11 18:57 UTC, benasher44 commented
@khanayan123 maybe this could be in the v5 preview — people can test it out 😅 🙏

2024-01-11 19:23 UTC, Qard requested changes
Looks like it's mostly just the change of `export default tracer` to `export = tracer` that matters here? What's the reason for all the other changes? Are those necessary? I worry a bit that so much structural changes might make this need to be a semver major change. 🤔 

Also, looks like a few things changed that should not.

2024-01-11 19:23 UTC, Qard commented on index.d.ts
> +  trace<T> (name: string, options: tracer.TraceOptions & tracer.SpanOptions, fn: (span?: tracer.Span, done?: (error?: Error) => string) => T): T;
This change is incorrect. There is no done function which returns a string.

2024-01-11 19:23 UTC, Qard commented on index.d.ts
> +  trace<T> (name: string, fn: (span?: tracer.Span, fn?: (error?: Error) => any) => T): T;
This was split into two signatures both of which _require_ that span is handled.

2024-01-11 19:30 UTC, benasher44 commented
Ah whoops will fix those issues — thanks for flagging!

You're right that's the main focus, but in switching to `export =`, it cascades (the reason for the other changes). Once you have `export =`, that has the be the sole export (TS errors). To then support all of the other named exports, you move them into the namespace and re-export them there. In doing that, you then have to remove all of the `declare`, since declare is only valid/necessary at the top level.

2024-01-11 19:38 UTC, benasher44 commented on index.d.ts
> +  export type SpanOptions = opentracing.SpanOptions;
This is done this way to force TS to see this as a type import and not a value import (which isn't allowed in a namespace)

2024-01-11 19:38 UTC, benasher44 commented on index.d.ts
> +  export type SpanOptions = opentracing.SpanOptions;
(as opposed to including it in the below export)

2024-01-11 19:44 UTC, benasher44 commented on index.d.ts
> -interface Plugins {
moved to top level to avoid exporting (see comment)

2024-01-11 19:46 UTC, benasher44 commented on index.d.ts
> -      deduplicationEnabled?: boolean
seems like this comma should have been required before 🤔

2024-01-11 19:48 UTC, benasher44 commented
Okay I've re-reviewed the diff a few more times to try to ensure as little outside of the restructuring that's needed has been (aside from a stray missing comma I called out).

2024-01-11 20:00 UTC, benasher44 commented
Before this change, output of [attw](https://github.com/arethetypeswrong/arethetypeswrong.github.io/tree/main/packages/cli):

<img width="809" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/1120429/d3e9a94a-814a-4110-8558-d954fe9e37dc">

After this change, output of attw:

<img width="486" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/1120429/7c3bc87c-8af6-4fff-8045-14c1f4fafeb5">

Results were gotten by running `attw` on the result of `npm pack` on master and then again on the result of running `npm pack` on this PR. So at least on that front, this PR accomplish its type compatibility goals.

2024-01-11 20:13 UTC, benasher44 commented on index.d.ts
> +  tracer: Tracer;
caught by `yarn type:test`

2024-01-16 19:22 UTC, benasher44 commented
> I worry a bit that so much structural changes might make this need to be a semver major change.

AFAICT, test coverage should confirm that these type updates are compatible, but I'm happy to open a PR to first improve coverage, if that'd be more comfortable. There are some uncovered exports, but it looks it looks like the major ones are covered by docs/test.ts:

```ts
import ddTrace, { tracer, Tracer, TracerOptions, Span, SpanContext, SpanOptions, Scope, User } from '..';
import type { plugins } from '..';
import { opentelemetry } from '..';
```

2024-01-16 19:28 UTC, benasher44 commented
Also happy to make myself available for quick follow up fixes if I'm wrong 🤞

2024-01-17 18:16 UTC, Qard approved these changes

2024-01-17 18:38 UTC, benasher44 commented
🙌  thanks!

For the failures: many are HTTP errors — maybe it being my commit (so my user?) or something is causing an issue? I'm not sure whether the others are expected.

Let me know, and I'm happy to update with master, if needed.

2024-02-05 15:55 UTC, benasher44 commented
Hi @Qard! I wanted to check in to see what you might need from me to be able to merge this, or if there might be something else you all are waiting on internally?

2024-02-14 17:00 UTC, benasher44 commented
Is it a confidence issue? If so, I'd be happy to open a PR to improve type test coverage first.

2024-02-15 15:59 UTC, Cellule commented
I tested real quick on my setup doing a dual cjs/esm build and this change fixes my problem for the esm build

2024-02-27 01:12 UTC, closed without merging