Api security enabled by default, sampling = 0 to disable it
DataDog/dd-trace-js pull request #4005
Opened 2024-01-26 14:16 UTC by uurien

### What does this PR do?

### Motivation

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

### Security 
Datadog employees:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2024-01-30 14:50 UTC, simon-id approved these changes

2024-02-01 22:30 UTC, Qard approved these changes

2024-02-02 09:10 UTC, simon-id requested changes
I just realized, the system-tests are not even enabled for this feature, the green CI is not to be trusted

2024-02-06 09:49 UTC, simon-id approved these changes

2024-02-06 10:01 UTC, merged