[ci-visibility] Disable telemetry for cypress plugin tests
DataDog/dd-trace-js pull request #4023
Opened 2024-02-02 13:15 UTC by juan-fernandez

### What does this PR do?
Disable telemetry for cypress plugin tests.

### Motivation
We're not testing anything regarding telemetry in the test, so at this point it's just noise. Also, plugin tests do not reflect very well how cypress tests are run, so I'm inclined to remove them altogether at some point. 

For the moment, disabling telemetry should make the occasional error go away.

### Security 
Datadog employees:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2024-02-02 14:40 UTC, ida613 submitted a review, later dismissed

2024-02-02 14:40 UTC, simon-id requested changes
little test ?

2024-02-02 15:43 UTC, juan-fernandez commented
now the test fails in a different way 😠. Only in CI too, locally there's no problem. I'll need to dig a bit more

2024-02-05 10:31 UTC, juan-fernandez commented
> now the test fails in a different way 😠. Only in CI too, locally there's no problem. I'll need to dig a bit more

ok found the issue. It's unrelated to this PR. It was a regression I introduced in https://github.com/DataDog/dd-trace-js/pull/4021. I merged the PR anyway, I probably thought the plugins were just flaking 😞

2024-02-05 11:30 UTC, romainkomorndatadog submitted a review, later dismissed

2024-02-05 13:58 UTC, simon-id commented on packages/dd-trace/test/telemetry/index.spec.js
> +  it('should send app-closing', () => {
```suggestion
  // TODO: test it's called on beforeExit instead of calling directly
  it('should send app-closing', () => {
```

2024-02-05 14:14 UTC, simon-id approved these changes

2024-02-05 14:35 UTC, romainkomorndatadog approved these changes

2024-02-05 17:44 UTC, merged