w3c: add last parent_id to tracestate
DataDog/dd-trace-js pull request #4118
Opened 2024-02-28 19:43 UTC by mabdinur

### What does this PR do?

With this change span_id will be encoded in both the tracestate and traceparent headers. This will allow us to re-connect datadog traces that contain non-datadog spans. 

Ex: Host A: Datadog Spans ->tracecontext-> Host B: Otel Dynatrace Spans -->tracecontext-> Host C: Otel Datadog Spans
By adding span_id to the tracestate Host C will be able to detect upstream Datadog spans from Host A. This span_id will then be sent to Datadog intake services (via `_dd.parent_id` tag). The Datadog internal services will use this tag to reconnect Datadog Spans.

### Motivation

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

### Security 
Datadog employees:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2024-02-29 20:20 UTC, khanayan123 reviewed
LGTM, but I will have to defer the approval of this PR to @rochdev since he might have some opinions on changes to tracestate

2024-03-05 02:02 UTC, rochdev approved these changes

2024-03-08 18:42 UTC, mabdinur commented
Blocked by: https://github.com/DataDog/dd-trace-js/pull/4153

2024-03-08 18:50 UTC, mabdinur commented on packages/dd-trace/src/opentracing/propagation/text_map.js
> +      state.set('p', spanContext._spanId)
```suggestion
     if (!spanContext._isRemote){
        # SpanContext was created by a ddtrace span. 
        # Last datadog span id should be set to the current span.
        state.set('p', spanContext._spanId)
     } else if (spanContext._trace.tags['_dd.parent_id']) {
        # Propagate the last Datadog span id set on the remote span.
        state.set('p', spanContext._trace.tags['_dd.parent_id'])
     }
```

2024-03-08 19:21 UTC, Qard commented on packages/dd-trace/src/opentracing/propagation/text_map.js
> +      state.set('p', spanContext._spanId)
Wrong comment syntax. 😅 

```suggestion
      if (!spanContext._isRemote) {
        // SpanContext was created by a ddtrace span. 
        // Last datadog span id should be set to the current span.
        state.set('p', spanContext._spanId)
      } else if (spanContext._trace.tags['_dd.parent_id']) {
        // Propagate the last Datadog span id set on the remote span.
        state.set('p', spanContext._trace.tags['_dd.parent_id'])
      }
```

2024-03-11 00:34 UTC, rochdev requested changes
Can a test for this be added?

2024-03-12 20:35 UTC, khanayan123 approved these changes

2024-03-12 21:54 UTC, rochdev approved these changes

2024-03-12 21:54 UTC, merged