v4.39.0
DataDog/dd-trace-js pull request #4373
Opened 2024-06-04 16:39 UTC by juan-fernandez

### Improvements
- Remove outdated polyfills [#4009](https://github.com/DataDog/dd-trace-js/pull/4009)
- Update native-appsec module to 8.0.1 [#4347](https://github.com/DataDog/dd-trace-js/pull/4347)
- profiler supports activation through single-step instrumentation [#4375](https://github.com/DataDog/dd-trace-js/pull/4375)

### Features
 - [ci-visibility] Support mocha parallel mode[#4314](https://github.com/DataDog/dd-trace-js/pull/4314)

### Bug fixes
- [ci-visibility] Fix EFD with jest and jsdom [#4323](https://github.com/DataDog/dd-trace-js/pull/4323)
- [ci-visibility] Fix selenium when run outside of a supported test framework[#4330](https://github.com/DataDog/dd-trace-js/pull/4330)

2024-06-04 16:49 UTC, tlhunter approved these changes

2024-06-04 16:50 UTC, tlhunter requested changes
Looks like we're missing the package.json version commit?

2024-06-05 15:36 UTC, iunanua approved these changes

2024-06-05 16:24 UTC, tlhunter approved these changes

2024-06-05 16:25 UTC, szegedi approved these changes
Good to go from profiling! 🚢

2024-06-05 16:25 UTC, szegedi approved these changes
Good to go from profiling! 🚢

2024-06-05 16:45 UTC, merged