fix(openai): safe require `tiktoken` for webpack bundlers
DataDog/dd-trace-js pull request #4433
Opened 2024-06-24 14:18 UTC by sabrenner

### What does this PR do?
Add-on to #4366, where we added support for leveraging `tiktoken` if it is installed to capture token metrics for the `openai` integration. However, this does not play nicely with `webpack`, which popular framework Next.js uses under the hood. The workaround involves setting `resolve.fallback.tiktoken = false` in `webpack.config.js` or `next.config.js`. However, to make using the tracer as seamless as possible, this fix wraps the require in a function to bypass this behavior (by not directly requiring it).

Additionally, cleans up some test logic and utilizes `tiktoken` as a dev dependency for regression purposes.

### Motivation
Fixes #4424 

The following webpack error would come up when bundling:
```
⚠ ../../node_modules/dd-trace/packages/datadog-plugin-openai/src/index.js
Module not found: Can't resolve 'tiktoken' in 'node_modules/dd-trace/packages/datadog-plugin-openai/src'
```

### Testing
#### Unit
Added `tiktoken` as a dev dependency for OpenAI tests. All tests now run against this, and any changes to that library or how we use it (ie typos) are reflected in failing tests. To test the in-house estimations, I moved the `estimateTokens` function into its own file, and added a small set of regression tests to assert basic behavior. This can be cleaned up more in a refactor of the OpenAI integration & tests in a future PR.

#### Local
Ran webpack on a test script importing `dd-trace`, before and after this fix. I was getting the error before, and not after. I was wondering why our Next.js tests weren't picking up on this, but I believe it's because of how we set up those tests, and how we use a `server.js` file, which I'm not sure gets compiled with webpack.

2024-06-24 20:10 UTC, tlhunter requested changes
Sam and I spoke OOB. Will need a test as the `encodingForModel` typo alluded.

2024-06-25 19:35 UTC, sabrenner commented on packages/datadog-plugin-openai/test/streamed-responses/completions.simple.txt
had to change the model here to be compatible with `tiktoken`

2024-06-25 19:36 UTC, sabrenner commented on packages/datadog-plugin-openai/test/index.spec.js
> +                expect(span.metrics).to.not.have.property('openai.response.usage.prompt_tokens_estimated')
this kind of change ensures we were able to use `tiktoken` correctly

2024-06-25 20:03 UTC, tlhunter approved these changes

2024-06-25 20:14 UTC, merged