Fix @types/node to version 18.x
DataDog/dd-trace-js pull request #4532
Opened 2024-07-18 14:58 UTC by watson

This project supports Node.js >=18.0.0, so the @types/node dependency should not be newer.

2024-07-18 19:17 UTC, bengl requested changes
Should this actually be ^16, since we support Node.js v16 on our 4.x release line?

2024-07-19 10:56 UTC, watson commented
@bengl I've downgraded to 16.x now and updated PR title/description to match

2024-07-22 19:51 UTC, Qard submitted a review, later dismissed

2024-07-22 21:09 UTC, bengl commented
LGTM except now there's a yarn lockfile conflict

2024-07-23 07:11 UTC, watson commented
* **#4532** <a href="https://app.graphite.dev/github/pr/DataDog/dd-trace-js/4532?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @watson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-23 10:03 UTC, watson commented
@bengl merge conflict resolved. Please re-review 😃

2024-07-25 14:13 UTC, bengl approved these changes

2024-07-25 14:13 UTC, merged