Upgrading jsonpath-plus to v10 to resolve CVE-2024-21534
DataDog/dd-trace-js pull request #4778
Opened 2024-10-14 13:44 UTC by juancarlosjr97

### What does this PR do?

Upgrading jsonpath-plus to v10 to resolve https://github.com/advisories/GHSA-pppg-cpfq-h7wr

### Motivation

Resolve #4770

### Additional Notes

2024-10-14 14:05 UTC, rafaelconcept approved these changes

2024-10-14 14:19 UTC, rafaelconcept commented
please add the label "semver-patch"

2024-10-14 14:23 UTC, juancarlosjr97 commented
It does not look I have permissions to add label @rafaelconcept

2024-10-14 15:17 UTC, simon-id requested changes
```
CHANGES for jsonpath-plus
10.0.0
BREAKING CHANGES:

Require Node 18+
```

We support down to Node 16.0.0

2024-10-14 15:19 UTC, simon-id commented
I'll forward this issue to the right place. But in the meantime we cannot merge this PR without more work because of jsonpath dropping support for node 16

2024-10-14 17:09 UTC, mrbrownt commented
@simon-id are we sure about that? It looks like v5 [dropped support](https://github.com/DataDog/dd-trace-js/commit/f4d32183e7630ae05fd93ca12631f24578df8c02) for node 16

2024-10-15 07:42 UTC, simon-id commented
@mrbrownt we have multiple release lines, please refer to that table
https://github.com/DataDog/dd-trace-js?tab=readme-ov-file#version-release-lines-and-maintenance

2024-10-15 08:29 UTC, simon-id commented
@tlhunter You've introduced this dependency to the repo, you should have more context than me

2024-10-15 09:38 UTC, narek-haytyan commented
> @simon-id are we sure about that? It looks like v5 [dropped support](https://github.com/DataDog/dd-trace-js/commit/f4d32183e7630ae05fd93ca12631f24578df8c02) for node 16

Actually according to the [`package.json`](https://github.com/DataDog/dd-trace-js/blob/944f57d5d4cc510b59d0966eb604bd1be585d82e/package.json#L76) the min supported version is 18.

@tlhunter can you please prioritize reviewing and merging this PR?

2024-10-15 11:11 UTC, juan-fernandez commented
> > ```
> > CHANGES for jsonpath-plus
> > 10.0.0
> > BREAKING CHANGES:
> > 
> > Require Node 18+
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We support down to Node 16.0.0
> 
> @simon-id actually according to the [`package.json`](https://github.com/DataDog/dd-trace-js/blob/944f57d5d4cc510b59d0966eb604bd1be585d82e/package.json#L76) the min supported version is 18.
> 
> @tlhunter can you please prioritize reviewing and merging this PR?

The v4 release line's min supported version is indeed 16, as seen in the [`package.json`](https://github.com/DataDog/dd-trace-js/blob/73b674f7d1a5e19be7765e0917e4da218b2f0e04/package.json#L76). 

Technically we could do this dependency bump only for v5, but that introduces some complexity. Aren't there any jsonpath-plus@v9 release with the vulnerability fixed? That'd be the best solution

2024-10-15 11:18 UTC, gaelperon commented
Thank you for your efforts :-) 

We are interested in the fix

We have an SLA running on this critical vulnerability

2024-10-15 11:20 UTC, juancarlosjr97 commented
> @juan-fernandez Technically we could do this dependency bump only for v5, but that introduces some complexity. Aren't there any jsonpath-plus@v9 release with the vulnerability fixed? That'd be the best solution

No, the released v10 with the security fix https://github.com/JSONPath-Plus/JSONPath/blob/main/CHANGES.md

2024-10-15 12:53 UTC, watson commented
Regarding this vulnerability in relation to the `dd-trace` package: **This package is not vulnerable to CVE-2024-21534.**

### Details

I've audited all locations in the the `dd-trace` source code that calls the `jsonpath-plus` package. These are my findings:

1. The only input given to the vulnerable function is from the [`cloudPayloadTagging`](https://datadoghq.dev/dd-trace-js/interfaces/export_.TracerOptions.html#cloudPayloadTagging) config option after it has been validated.
2. Because of this validation, it's not even possible for admins on the system to trigger this vulnerability.
3. End users have no way of manipulating this input.

We're aware that this will still come up in security scans, so this issue still has high priority. We're working on a solution so that we can publish a patch to both v4.x and v5.x that removes the vulnerable dependency.

2024-10-15 14:12 UTC, watson commented
Our CI system currently has an issue testing code from external contributors. To get around this issue for now, I've created a copy of this PR here: https://github.com/DataDog/dd-trace-js/pull/4782

The PR contains the same commit with the same author information. The only difference is that I've created the PR.

I'm going to close this PR. Please continue the discussion in the new PR, thank you.

2024-10-15 14:13 UTC, closed without merging

2024-10-15 14:16 UTC, juancarlosjr97 commented
All good, thank you for picking this up @watson :)