stop using native metrics for newer node versions
DataDog/dd-trace-js pull request #4952
Opened 2024-11-27 23:58 UTC by rochdev

### What does this PR do?

Stop using native metrics for newer Node versions.

### Motivation

All the runtime metrics we need are now available out of the box from Node, so loading a native extension is no longer necessary to capture them.

2024-11-28 10:37 UTC, juan-fernandez approved these changes

2024-11-28 13:02 UTC, szegedi approved these changes
This is great! One less native component to worry about.

2024-11-28 13:02 UTC, szegedi commented on packages/dd-trace/src/runtime_metrics.js
> +  (NODE_MAJOR === 22 && NODE_MAJOR >= 8) ||
```suggestion
  (NODE_MAJOR === 22 && NODE_MINOR >= 8) ||
```

2024-11-28 13:03 UTC, szegedi requested changes
This is great! One less native component to worry about. I think there's one type tho'.

2024-11-28 17:27 UTC, rochdev commented
Turns out the Node implementation is invalid, so this PR cannot work. I will open an issue in Node, but I think their implementation will have to be completely rewritten for this to work.

2024-12-13 19:42 UTC, rochdev commented
Superseded by #4961 since `monitorLoopDelay` is broken.

2024-12-13 19:42 UTC, closed without merging