env var to disable all middleware spans
DataDog/dd-trace-js pull request #5044
Opened 2024-12-19 13:47 UTC by bengl

### What does this PR do?

### Motivation

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Additional Notes

2025-01-23 15:36 UTC, bengl commented on packages/datadog-plugin-express/test/integration-test/client.spec.js
> +      process.env.DD_TRACE_MIDDLEWARE_ENABLED = true
```suggestion
      delete process.env.DD_TRACE_MIDDLEWARE_ENABLED
```

2025-01-23 22:13 UTC, tlhunter commented on packages/dd-trace/src/config.js
> +    this._setValue(defaults, 'middleware', true)
This name seems too simple and easy to confuse the purpose. How about `enableMiddlewareTracing`?

2025-01-24 15:37 UTC, bengl commented on packages/dd-trace/src/config.js
> +    this._setValue(defaults, 'middleware', true)
I prefer this name, yes.

2025-01-28 21:29 UTC, tlhunter approved these changes

2025-01-29 19:20 UTC, tlhunter submitted a review, later dismissed

2025-01-29 21:19 UTC, tlhunter approved these changes

2025-01-29 21:43 UTC, tlhunter submitted a review, later dismissed

2025-01-30 09:25 UTC, rochdev requested changes

2025-01-30 09:25 UTC, rochdev commented on packages/datadog-plugin-express/test/integration-test/client.spec.js
> +      delete process.env.DD_TRACE_MIDDLEWARE_ENABLED
Altering environment variables should be done in `beforeEach` and `afterEach` to make sure that the previous value is restored.

2025-01-30 09:25 UTC, rochdev commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
The environment variable doesn't match the name of the programmatic option.

2025-01-30 09:25 UTC, rochdev commented on packages/dd-trace/src/plugins/util/web.js
> +    } else if (config.hasOwnProperty('middlewareTracingEnabled')) {
This should be done in the plugin manager, consistent with other similar options. While it could be argued that this is not ideal, changing how this works is out of scope of this PR.

2025-01-30 09:25 UTC, rochdev commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
It also doesn't have a corresponding test.

2025-01-30 14:36 UTC, bengl commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
> The environment variable doesn't match the name of the programmatic option.

Please provide suggested values for both. @tlhunter @rochdev please coordinate on this because right now you folks have both made naming suggestions.

> It also doesn't have a corresponding test.

I don't understand this comment. In this same review, you commented on the corresponding test. What additional testing are you looking for?

2025-01-30 14:40 UTC, bengl commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
> The environment variable doesn't match the name of the programmatic option.

Please provide suggested values for both. @tlhunter @rochdev please coordinate on this because right now you folks have both made naming suggestions.

> It also doesn't have a corresponding test.

I don't understand this comment. In this same review, you commented on the corresponding test. What additional testing are you looking for?

2025-01-30 15:33 UTC, rochdev commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
> Please provide suggested values for both.

I don't mind the name, but it should map between programmatic and env var.

> I don't understand this comment. In this same review, you commented on the corresponding test.

The plugin test yes, but there isn't a test for the option itself (config.spec.js)

2025-01-30 15:43 UTC, bengl commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
>I don't mind the name, but it should map between programmatic and env var.

So renaming the env var to `DD_TRACE_MIDDLEWARE_TRACING_ENABLED` would be sufficient? That's a lot of `TRACE` in the name, but I guess that's fine.

2025-01-30 15:53 UTC, rochdev commented on packages/dd-trace/src/config.js
> +      DD_TRACE_MIDDLEWARE_ENABLED,
> That's a lot of TRACE in the name, but I guess that's fine.

We did name the library `dd-trace` after all 😅

2025-01-30 17:15 UTC, rochdev approved these changes

2025-01-30 19:12 UTC, merged